#!/bin/bash

SCRIPT_DIR=$(realpath $(dirname $0))




export QVM_ARCH="ppc"
export QVM_MACHINE="mac99"

export QVM_CPU="G4"
export QVM_CPU_CORES="1"

export QVM_INCLUDE_USB="1"
export QVM_INCLUDE_NETWORK="1"

export QVM_EXTRA_DEVICES="-device usb-kbd -device usb-tablet "


${SCRIPT_DIR}/boot_qemu_machine
