#!/bin/bash

SCRIPT_DIR=$(realpath $(dirname $0))




export QVM_NAME="Tiger"
export QVM_RAM="1G"
export QVM_HDA="harddrives/OS_X_Tiger_PPC.qcow2"
export QVM_SPICE_PORT="50020"


if [ "$1" == "--install" ];
then
    export QVM_BOOT_ORDER="d"
else
    export QVM_BOOT_ORDER="c"
fi


$SCRIPT_DIR/boot_ppc_mac


