#!/bin/bash

if [ "$MAC_HD" == "" ];
then
    echo "No Mac config loaded detected. First, load one with:"
    echo "source <config file> or . <config file>."
    echo ""

    exit 1
fi

echo "Config for $QEMU_VM_NAME loaded."
echo ""




# ==========================================================================
# DO NOT TOUCH ANYTHING BELOW THIS POINT UNLESS YOU KNOW WHAT ARE YOU DOING.
#
# You can customice many things exporting the corresponding variables
# before executing this script. Then, your values will be used instead
# default ones.
# ==========================================================================

SCRIPT_DIR=$(realpath $(dirname $0))

# ------ ADVANCED CONFIG AREA ---------
if [ "$CPU_OPTS" == "" ];
then
    CPU_OPTS="vendor=GenuineIntel,kvm=on,"
    CPU_OPTS+="+sse3,+sse4.2,+aes,+xsave,+avx,+xsaveopt,+xgetbv1"
    CPU_OPTS+=",+avx2,+bmi2,+smep,+bmi1,+fma,+movbe,+invtsc"
fi

if [ "$AUDIO_DEVICE" == "" ];
then
    AUDIO_DEVICE="ich9-intel-hda"
fi

if [ "$DISK_CONTROLLER" == "" ];
then
    DISK_CONTROLLER="ich9-ahci"
fi

if [ "$MAC_NETWORK_MAC" == "" ];
then
    MAC_NETWORK_MAC="52:54:00:c9:18:27"
fi

if [ "$BOOT_DRIVE_BUS" == "" ];
then
    BOOT_DRIVE_BUS="DISK.1"
fi

if [ "$CD_DRIVE_BUS" == "" ];
then
    CD_DRIVE_BUS="DISK.2"
fi

if [ "$HD1_DRIVE_BUS" == "" ];
then
    HD1_DRIVE_BUS="DISK.3"
fi

if [ "$HD2_DRIVE_BUS" == "" ];
then
    HD2_DRIVE_BUS="DISK.4"
fi

if [ "$HD3_DRIVE_BUS" == "" ];
then
    HD3_DRIVE_BUS="DISK.5"
fi

if [ "$HD4_DRIVE_BUS" == "" ];
then
    HD4_DRIVE_BUS="DISK.6"
fi

if ! [ "$EFI_CODE_PATH" == "NONE" ] && [ "$EFI_CODE_PATH" == "" ];
then
    EFI_CODE_PATH="$SCRIPT_DIR/EFI/OVMF_CODE.fd"
    EFI_VARS_PATH="$SCRIPT_DIR/EFI/OVMF_VARS.fd"
fi

if [ "$BOOT_IMAGE" == "" ];
then
    BOOT_IMAGE="$SCRIPT_DIR/bootloader/OpenCore.img"
fi

if [ "$BOOTLOADER_DEVICE" == "" ];
then
    if [[ $BOOT_IMAGE == *.qcow2 ]];
    then
        # Boot image format
        BIF="qcow2"
    else
        BIF="raw"
    fi

    BOOTLOADER_DEVICE="ide-hd,bus=${BOOT_DRIVE_BUS},drive=Bootloader"
    BOOTLOADER_DRIVE="if=none,format=${BIF},media=disk,id=Bootloader"
    BOOTLOADER_DRIVE+=",file=${BOOT_IMAGE}"
fi

if ! [ "$MAC_DVD" == "NONE" ] && [ "$CD_DEVICE" == "" ];
then
    CD_DEVICE="ide-cd,bus=${CD_DRIVE_BUS},drive=DVD-RW"
    CD_DRIVE="if=none,format=raw,readonly=on,media=cdrom,id=DVD-RW"
    CD_DRIVE+=",file=${MAC_DVD}"
fi

#if [ "$HD_DEVICE" == "" ];
#then
#    HD_DEVICE="ide-hd,bus=${HD_DRIVE_BUS},drive=HardDrive"
#    HD_DRIVE="if=none,format=qcow2,media=disk,id=HardDrive,file=${MAC_HD}"
#fi

if ! [ "$MAC_HD" == "" ];
then
    if [[ $MAC_HD == *.qcow2 ]];
    then
        # HD image format
        HIF="qcow2"
    else
        HIF="raw"
    fi

    HD1_DEVICE="ide-hd,bus=${HD1_DRIVE_BUS},drive=HardDrive"
    HD1_DRIVE="if=none,format=${HIF},media=disk,id=HardDrive,file=${MAC_HD}"
fi

if ! [ "$MAC_HD_2" == "" ];
then
    if [[ $MAC_HD_2 == *.qcow2 ]];
    then
        # HD image format
        HIF="qcow2"
    else
        HIF="raw"
    fi

    HD2_DEVICE="ide-hd,bus=${HD2_DRIVE_BUS},drive=HD2"
    HD2_DRIVE="if=none,format=${HIF},media=disk,id=HD2,file=${MAC_HD_2}"
fi

if ! [ "$MAC_HD_3" == "" ];
then
    if [[ $MAC_HD_3 == *.qcow2 ]];
    then
        # HD image format
        HIF="qcow2"
    else
        HIF="raw"
    fi

    HD3_DEVICE="ide-hd,bus=${HD3_DRIVE_BUS},drive=HD3"
    HD3_DRIVE="if=none,format=${HIF},media=disk,id=HD3,file=${MAC_HD_3}"
fi

if ! [ "$MAC_HD_4" == "" ];
then
    if [[ $MAC_HD_4 == *.qcow2 ]];
    then
        # HD image format
        HIF="qcow2"
    else
        HIF="raw"
    fi

    HD4_DEVICE="ide-hd,bus=${HD4_DRIVE_BUS},drive=HD4"
    HD4_DRIVE="if=none,format=${HIF},media=disk,id=HD4,file=${MAC_HD_4}"
fi

# -------------------------------------




OSK="ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"

QEMU="qemu-system-x86_64"
QEMU_OPTS=""


if ! [ "$QEMU_VM_NAME" == "" ];
then
    QEMU_OPTS+="" #-name \"${QEMU_VM_NAME}\" "
fi

QEMU_OPTS+="-enable-kvm "
QEMU_OPTS+="-m ${MAC_RAM} "
QEMU_OPTS+="-machine q35,accel=kvm "
QEMU_OPTS+="-smp 4,cores=${MAC_CORES} "
QEMU_OPTS+="-cpu Penryn,${CPU_OPTS} "
QEMU_OPTS+="-device isa-applesmc,osk=${OSK} "
QEMU_OPTS+="-smbios type=2 "

if ! [ "$EFI_CODE_PATH" == "NONE" ];
then
    QEMU_OPTS+="-drive if=pflash,format=raw,readonly=on"
    QEMU_OPTS+=",file=${EFI_CODE_PATH} "
    
    QEMU_OPTS+="-drive if=pflash,format=raw"
    QEMU_OPTS+=",file=${EFI_VARS_PATH} "
fi

if ! [ "$MAC_GRAPHICS" == "" ];
then
    QEMU_OPTS+="$MAC_GRAPHICS "
else
    QEMU_OPTS+="-vga qxl "
fi

if ! [ "$HEADLESS" == "1" ];
then
    QEMU_OPTS+="-display gtk "
else
    QEMU_OPTS+="-display none "
fi

if ! [ "MAC_SPICE_PORT" == "" ];
then
    QEMU_OPTS+="-spice port=${MAC_SPICE_PORT},addr=0.0.0.0"
    QEMU_OPTS+=",disable-ticketing=on "
fi

QEMU_OPTS+="-device $AUDIO_DEVICE "
QEMU_OPTS+="-device hda-output "
QEMU_OPTS+="-usb "
QEMU_OPTS+="-device usb-kbd "
QEMU_OPTS+="-device usb-tablet "
QEMU_OPTS+="-netdev user,id=net0 "
QEMU_OPTS+="-device e1000-82545em,netdev=net0,id=net0,mac=$MAC_NETWORK_MAC "
QEMU_OPTS+="-device $DISK_CONTROLLER,id=DISK "

QEMU_OPTS+="-drive ${BOOTLOADER_DRIVE} "
QEMU_OPTS+="-device ${BOOTLOADER_DEVICE} "

if ! [ "$MAC_DVD" == "NONE" ];
then
    QEMU_OPTS+="-drive ${CD_DRIVE} "
    QEMU_OPTS+="-device ${CD_DEVICE} "
fi

QEMU_OPTS+="-drive ${HD1_DRIVE} "
QEMU_OPTS+="-device ${HD1_DEVICE} "

if ! [ "$MAC_HD_2" == "" ];
then
    QEMU_OPTS+="-drive ${HD2_DRIVE} "
    QEMU_OPTS+="-device ${HD2_DEVICE} "
fi

if ! [ "$MAC_HD_3" == "" ];
then
    QEMU_OPTS+="-drive ${HD3_DRIVE} "
    QEMU_OPTS+="-device ${HD3_DEVICE} "
fi

if ! [ "$MAC_HD_4" == "" ];
then
    QEMU_OPTS+="-drive ${HD4_DRIVE} "
    QEMU_OPTS+="-device ${HD4_DEVICE} "
fi


#echo "$QEMU $QEMU_OPTS"

$QEMU $QEMU_OPTS
