#!/bin/bash

SCRIPT_DIR=$(realpath $(dirname $0))




export QVM_NAME="SnowLeopard"

export QVM_CPU="Penryn"
export QVM_CPU_OPTS="vendor=GenuineIntel,+sse3,+sse4.1,+sse4.2"
export QVM_CPU_CORES="2"
export QVM_RAM="2G"

export QVM_EFI="EFI/i386/OVMF_CODE.fd"
export QVM_EFI_VARS="EFI/i386/OVMF_VARS.fd"

export QVM_IDE_0_MASTER="bootloader/_testing/ESP.qcow2"
export QVM_IDE_0_SLAVE="harddrives/SnowLeopard.qcow2"
export QVM_IDE_1_MASTER="iso/OS_X_Leopard.iso"


$SCRIPT_DIR/boot_intel_mac


