#!/bin/bash

SCRIPT_DIR=$(realpath $(dirname $0))

export QEMU_VM_NAME="Mac OS X Leopard"
export MAC_VERSION_MAJOR="10"
export MAC_VERSION_MINOR="5"
export MAC_RAM="2G"
export MAC_CORES="2"
export MAC_DVD="NONE"
export MAC_HD="harddrives/Leopard.qcow2"
#export MAC_GRAPHICS="-vga qxl"
export MAC_SPICE_PORT="50020"

#export EFI_CODE_PATH="NONE"
#export BOOT_IMAGE="bootloader/OpenCore-amd64.img"
export BOOT_IMAGE="bootloader/OpenCore.qcow2"

$SCRIPT_DIR/boot_intel_mac


